### ISSUE TITLE
Set-AtwsResource InternalCost

### ISSUE THREAD

**Issue by me1299** [ecitsolutions/Autotask#100]
When I try to alter the internal cost of a resource nothing seems to happen.

```powershell
$resources = Get-AtwsResource -Filter {FirstName -eq "Redacted"}
$resources | ForEach-Object {$_.InternalCost = 0}
$resources | Set-AtwsResource
```

I'm expecting the value to be set to 0 but they remain the same as they were. Other values I can alter just fine.

**Comment by JsonWud** [comment]
According to the SOAP API documentation, InternalCost is a read-only property:
https://www.autotask.net/help/developerhelp/Content/AdminSetup/2ExtensionsIntegrations/APIs/SOAP/Entities/ResourceEntity.htm

**Comment by bjowol** [comment]
> According to the SOAP API documentation, InternalCost is a read-only property:
> https://www.autotask.net/help/developerhelp/Content/AdminSetup/2ExtensionsIntegrations/APIs/SOAP/Entities/ResourceEntity.htm

This would explain the challenge.
A new beta module is to be released this week. This will properly throw errors from the SOAP API if any is returned. If the SOAP API returns an error regarding this property being read only, it would be easy to see that in the error message. It does return errors like "this resource does not have permission do to this action" like a charm.
