### ISSUE TITLE
New menu options not part of set when trying to query

### ISSUE THREAD

**Issue by PhoenixC46** [ecitsolutions/Autotask#101]
A few days ago we created some new Issue/SubIssue types and nothing seems to bring those options through for me to select when querying tickets or creating new.
For example: Get-AtwsTicket -IssueType "Productivity"
Returns the error: Get-AtwsTicket : Cannot validate argument on parameter 'IssueType'. The argument "Productivity" does not belong to the set "_(hidden values)_" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

The module is up to date, i've ran the Update-AtwsDiskCache and Update-AtwsFunctions -FunctionSet Dynamic commands but it makes no difference.
Is this a bug in the version or is there some other step that needs to be performed?
Thanks

**Comment by PhoenixC46** [comment]
The mystery of working in IT... fighting something constantly for 3 days, get fed up trying all sorts of fixes and finally log an issue.
Then the damn thing starts working almost instantly after.
3 DAYS!!! and then Poof! Magic! :-)
Doh!

**Comment by bjowol** [comment]
> The mystery of working in IT... fighting something constantly for 3 days, get fed up trying all sorts of fixes and finally log an issue.
> Then the damn thing starts working almost instantly after.
> 3 DAYS!!! and then Poof! Magic! :-)
> Doh!

hah what a world we live in huh?! :P 

cache storage locations, and powershell version differences is one thing to be aware of when debugging the module. Delete everything and just keep one autotask module version to make sure powershell is using the correct module version, cache location and updated cache ofc.
Did you have the build-atwsmodule cmdlet available?
