### ISSUE TITLE
Loading time of the module - specifically within Azure

### ISSUE THREAD

**Issue by TimBrown-CCS** [ecitsolutions/Autotask#102]
We use your module within Azure to automate certain processes, and the loadtime is beginning to be a bit of an issue. Specifically, we are currently working with Azure Functions to run an API, and it needs to connect to Autotask for some of the functions. 

It can take upwards of 3 minutes to load the module, which doesn't leave a lot of headroom for the rest of the process to run before the request times out.

Is there a way to only load certain entities into the module, so that we only load the ones we need and not all 167?

Thanks
Tim

**Comment by bjowol** [comment]
The beta module, currently beeing worked on to rule out kinks in ps 5.1 has a lot of speed improvements. 
You can expect to see a lot better performance in Core with the current Beta module. test it out if you will.

Also, put the loading of the module inside the profile.ps1 file. Mak use of the cold start feature. If your app is used frequently enough, and it prohibits sleep, or you get a premium app plan it wont go to sleep, then you can expect a lot better performance. 

did some testing locally, and its a lot faster to retrieave account -id 0 within an azure function.
This test is with module load inside run.ps1, not inside profile.ps1
![image](https://user-images.githubusercontent.com/14833255/119129404-26b07c00-ba37-11eb-8a66-fbca07502bbe.png)

**Comment by TimBrown-CCS** [comment]
Thanks a lot for your help. I've not looked too much at the beta, but I will check that out.

**Comment by TimBrown-CCS** [comment]
Ran some tests, and this appears to be the solution. Thanks @bjowol for fixing my lack of knowledge!
