### ISSUE TITLE
Exception calling GetFieldInfo

### ISSUE THREAD

**Issue by Octopistachio** [ecitsolutions/Autotask#104]
Today I started receiving this error when trying to import the Autotask module. 
```
Exception calling "GetFieldInfo" with "2" argument(s): "The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received 
from the server was 'Basic Realm="webservices15.autotask.net"'."
At C:\Users\itadmin\Documents\WindowsPowerShell\Modules\Autotask\2.0.0\Private\Update-AtwsEntity.ps1:56 char:17
+ ...             $result = $Script:Atws.GetFieldInfo($Script:Atws.Integrat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : MessageSecurityException
```

I replaced the original line `Import-Module "Autotask" -ArgumentList $Credential,$ApiTrackingIdentifier ` with `$configuration = New-AtwsModuleConfiguration -Credential $Credential -SecureTrackingIdentifier $ApiTrackingIdentifier -ProfileName Default` but it all my tests result in an exception

**Comment by bjowol** [comment]
double check your username, password and Tracking Identifier.

Also, you dont need to connect to the API using new-atwsModuleConfiguration. 
you can use Connect-AtwsWebAPI -Credential $creds -TrackingIdentifier $ti and after successful connection, use save-atwsModuleConfiguration -Name Default.

After that you dont really need to think about connecting or importing the module again, as there is autodiscover on the CMDlets, and the module will connect when it needs to by itself.

**Comment by bjowol** [comment]
bump @Octopistachio

**Comment by AceOfNitwits** [comment]
I'm having the same problem. I know the credentials and API key are correct, because they work with the prior versions of the module.

Here's what I get: (This was a manual connection test.)

`> Connect-AtwsWebAPI                        

PowerShell credential request
Your Autotask API user
User: AutotaskAPI@********.com
Password for user AutotaskAPI@********.com: ****************
API Tracking Identifier: ***************************
WARNING: Do you want to save these credentials as your Default connection profile? It will be encrypted using SecureString and encoded in CliXML. See Get-Help Set-AtwsModuleConfiguration for how to modify it.
Save connection credentials
Is it OK to save your credentials to your $Profile folder?
[Y] Yes [N] No [S] Suspend [?] Help (default is "Yes"): y
[##################------------]  60 % - Testing connection                     Exception: C:\Users\********\My Documents\PowerShell\Modules\Autotask\2.0.0\Private\Update-AtwsEntity.ps1:56:17
Line |
  56 |  …             $result = $Script:Atws.GetFieldInfo($Script:Atws.Integrat …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetFieldInfo" with "2" argument(s): "The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic
     | Realm="webservices3.autotask.net"'."`

**Comment by bjowol** [comment]
minor observation, your both using the American Zones. Does your password contain any special characters affected by encoding?
Can you both check this?: https://github.com/ecitsolutions/Autotask/issues/92#issuecomment-792704767

Also, be mindful how powershell handles $ inside a double quoted string "" and not a singular ''. '$len@bru' would be <$len@bru> but "$len@bru" would be: <bru> as "$lenxx" would be a variable reference. This only applies if you've pasted the password inside a string further up in your code.

**Comment by klemmestad** [comment]
This is a bug. I must doing something wrong, or at least too simplistic in the SOAP client setup. When I change the API user password to a complex secret the connection fails. I am investigating.

**Comment by klemmestad** [comment]
@AceOfNitwits, what is the output from `[net.servicepointmanager]::SecurityProtocol`on your system? Should be Tls12 by default, but just in case...

**Comment by AceOfNitwits** [comment]
@klemmestad 
Output is simply, `SystemDefault`.

The following might be of use in your investigation:
https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol?view=net-5.0

**Comment by Octopistachio** [comment]
> double check your username, password and Tracking Identifier.
> 
> Also, you dont need to connect to the API using new-atwsModuleConfiguration.
> you can use Connect-AtwsWebAPI -Credential $creds -TrackingIdentifier $ti and after successful connection, use save-atwsModuleConfiguration -Name Default.
> 
> After that you dont really need to think about connecting or importing the module again, as there is autodiscover on the CMDlets, and the module will connect when it needs to by itself.

This resolved my issue. My new line of code to connect to the API is as follows.
`Connect-AtwsWebAPI -Credential $Credential -ApiTrackingIdentifier $ApiKey`

**Comment by klemmestad** [comment]
@AceOfNitwits 
Then we need to double check the roundtrip to and from securestring. It looks like you saved your connection profile before the connection failed. Could you verify that your password has been captured correctly by reversing it like this:
```powershell
$SecureString = (Get-AtwsModuleConfiguration -Name 'Default').SecurePassword
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureString)
[System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($BSTR)
```
The output should be your password in clear text. To check your API key start with this as the first line:
```powershell
$SecureString = (Get-AtwsModuleConfiguration -Name 'Default').SecureTrackingIdentifier
```

**Comment by bakerthejosh** [comment]
Wanted to add to this, I was receiving the above issue with Azure Automation running the AutoTask module. The issue ended up being the complexity of the password being generated by AutoTask as the API secret. Utilizing a 'hand jammed' password that removed special characters resolved the issue.

**Comment by AndrewNZL** [comment]
Hey, I'm having a similar issue to this one.

My error is: 
Exception calling "GetFieldInfo" with "2" argument(s): "The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 
'Basic Realm="webservices6.autotask.net"'."
At C:\Program Files\WindowsPowerShell\Modules\Autotask\2.0.1\Private\Update-AtwsEntity.ps1:56 char:17
+ ...             $result = $Script:Atws.GetFieldInfo($Script:Atws.Integrat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : MessageSecurityException
    
My script was working fine untill i tried to embed the username and password using the example code for the powershell module:
$User = 'username'
$PWord = ConvertTo-SecureString -String 'long password with every character type' -AsPlainText -Force
$Credential = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $User, $PWord
$ApiTrackingIdentifier = ConvertTo-SecureString -String 'long string with no special characters' -AsPlainText -Force

Now even after deleting my profile file and re-connecting with Connect-AtwsWebApi and typing the username, apsswor dand tracking identified, it still gives me this error. I basically can't use the module/autotask api anymore.

Can anyone offer any assistance?

**Comment by klemmestad** [comment]
If you haven't tried it already, I would suggest a reboot. For some reason it may sometimes be impossible to change the in-memory credentials that .NET uses when calling the API. I can find myself locked to the Sandbox, the production instance, or - like in your case - locked to an outdated set of credentials. So far, the only sure way of clearing that out has been a reboot. Killing all your powershell processes does not clear it out. There probably is another process or thread that could be killed, but I haven't been able to figure out which it may be. The .NET SOAP client is created outside your powershell processes, and I just don't know enough about how .NET is implemented to figure out what to do outside a reboot.
