### ISSUE TITLE
Expose Knowledgebase Articles endpoints

### ISSUE THREAD

**Issue by yeneradal** [ecitsolutions/Autotask#105]
Hi there,

Love this library. Thanks for creating.

Just wanted to add this as an enhancement.

Any chance of allowing us to CRUD Knowledgebase articles?

Thanks

**Comment by klemmestad** [comment]
Hi @yeneradal,
Unfortunately, as far as I know there are no way to work with knowledgebase articles through REST nor SOAP with the Autotask APIs. I don't know of any workarounds either. If they add support for it in the API we will add it to our module ASAP :)

**Comment by yeneradal** [comment]
Hi Hugo,

Thanks for the reply.

I might be mistaken but I found these pages on the developer help.

Are they relevant?

- https://ww6.autotask.net/help/DeveloperHelp/Content/APIs/REST/Entities/KnowledgeBaseArticlesEntity.htm
- https://ww6.autotask.net/help/DeveloperHelp/Content/APIs/REST/Entities/KnowledgeBaseCategoriesEntity.htm
- https://ww6.autotask.net/help/DeveloperHelp/Content/APIs/REST/Entities/ArticleToDocumentAssociationsEntity.htm
- https://ww6.autotask.net/help/DeveloperHelp/Content/APIs/REST/Entities/ArticleAttachmentsEntity.htm

There's a few more too.

Thanks

**Comment by klemmestad** [comment]
You are right and I am wrong. Unfortunately it seems that KnowledgeBase related entities are only available through the REST api and not the SOAP api. I am afraid it will be months until I am ready to switch to the REST api...
