### ISSUE TITLE
Filtering by Tickets without FirstResponseDateTime

### ISSUE THREAD

**Issue by pbundschuh** [ecitsolutions/Autotask#107]
FIltering tickets by empty property "FirstResponseDateTime" does not work.

Get-AtwsTicket -Filter { FirstResponseDateTime -eq '' }

**Comment by klemmestad** [comment]
Hm, it seems my explicit filter handling is too dumb to understand $null values. I will look into that. But unless you really need to use explicit filters you may search for empty properties using parameters:

`Get-AtwsTicket -FirstResponseDateTime $null`
`# or`
`Get-AtwsTicket -IsNull FirstResponseDateTime`

Does that solve your use case?

**Comment by pbundschuh** [comment]
That works:
`Get-AtwsTicket -Filter { FirstResponseDateTime -IsNull }`
Thanks
