### ISSUE TITLE
Response Time Passed

### ISSUE THREAD

**Issue by MadRainbow** [ecitsolutions/Autotask#111]
Quick on guys,

Is there a way of finding out the time between a tickets creation date, and the first response in working hours?

I know that there are fields for both Creation Date, and First Response Date and Time, however the UI displays the time that's passed with is working or supported time.  Is this information available, or do I have to go to great lengths and come up with a complex calculation taking in our opening hours & holiday days?

Thanks

D

**Comment by klemmestad** [comment]
Hi @MadRainbow, sorry about the terribly late reply. As far as I can tell you will have to the calculation yourself. There are no properties on a ticket that holds this information.
