### ISSUE TITLE
Account Team

### ISSUE THREAD

**Issue by ws6jay** [ecitsolutions/Autotask#112]
I am looking for a way to bulk modify the Account Team for a list of clients in Autotask. I see that Account Manager is available, but not Accoutn Team.
Is this currently a function of this solution and i'm just not finding it? We assign team members to each client and I'm looking for a way to bulk add/replace team members based on a CSV list of accounts and also if a team member is replaced so we can quickly reassign their clients to a new hire.
Thanks!

**Comment by klemmestad** [comment]
Hi @ws6jay, sorry about the terribly late reply. You should be able to access AccountTeam using Get-AtwsAccountTeam, Remove-AtwsAccountTeam, and New-AtwsAccountTeam. There are no support for editing it, so I guess you will need to delete it first and then create a new one with the correct members.
