### ISSUE TITLE
Feature Request: LiveReport Designer

### ISSUE THREAD

**Issue by carterduplessis** [ecitsolutions/Autotask#113]
As far as I could find, there is no control over LiveReport Designer. We create reports for our partners all the time by cloning a template and inputting a few parameters then saving. Some functionality for this would save us hundreds of hours. 

I wonder if the REST API even covers LiveReport Designer though.

**Comment by klemmestad** [comment]
Hi @carterduplessis, sorry about the terribly late reply. No, there is no way to control LiveReport Designer through the API, I'm afraid.

**Comment by carterduplessis** [comment]
Yeah I learned that shortly after asking. I should have come back here to close this. Thanks!
