### ISSUE TITLE
Domain Name Monitoring

### ISSUE THREAD

**Issue by MadRainbow** [ecitsolutions/Autotask#114]
I have the Domain and SSL monitoring service from AT as part of our subscriptions.

Looking at get-atwsinstalledproduct I can't see the Domain Name field is being pulled through from the config items.  Whilst not a major problems, it seems we can't add the domain name field either with the new-atwsinstalledproduct command.

Does anyone know a way around this?  

Thanks

David

**Comment by klemmestad** [comment]
No, unfortunately this is the same limitation as issue #116: This module was written when the SOAP API was the only option. And the features you are missing are only exposed through the REST API. I have looked into switching backend of the module, but the two APIs are so different in terms of entity names and properties that existing scripts that use the current module would break if I switch.
