### ISSUE TITLE
New-AtWsTicket - setting ticket work type

### ISSUE THREAD

**Issue by LedgerLand** [ecitsolutions/Autotask#117]
I think I may well be loosing it, or just going blind, but when creating a ticket in Autotask you can set a "Work Type" on the ticket itself which is then the default for all time entries. However, I can't seem to find the correct option when using the New-AtWsTicket function. Is it available and, if so, where is it set?

**Comment by klemmestad** [comment]
You are right, you can't set "work type" on a ticket. There are no such property exposed on the Ticket entity through the API. However, I think you can set that property on a Ticket Category and then specify TicketCategory with New-AtwsTicket.

**Comment by LedgerLand** [comment]
Strange that they do not expose that element. Not thought of using the ticket category, I'll have a look at it.

Thanks!!
