### ISSUE TITLE
Not able to Delete ATWS Account Alerts

### ISSUE THREAD

**Issue by carterduplessis** [ecitsolutions/Autotask#120]
I only see the following cmdlets:

- Get-ATWSAccountAlert
- New-ATWSAccountAlert
- Set-ATWSAccountAlert

I don't see a way to remove or overwrite an account alert despite the Autotask API supporting it. https://www.autotask.net/help/developerhelp/Content/APIs/SOAP/Entities/AccountAlertEntity.htm

Am I missing something?

Carter

**Comment by carterduplessis** [comment]
I think this is something that has been added which is likely why it is missing from this powershell wrapper. Could this be added to the roadmap? This would save me having to write a function using the REST API which is where my comfort level is.

**Comment by klemmestad** [comment]
You are right. A rebuild of the module is long overdue. The SOAP API is supposedly in feature freeze, but support for removing accountalerts have definitely been added. I am Pestering the updated version tonight. Expect a release this week.

**Comment by carterduplessis** [comment]
Wow I didn't expect a reply so quick, much less a new release this week! This means so much to someone like me who proudly uses this PowerShell API wrapper every single day. I will eagerly await this release.

Thanks so much!

**Comment by klemmestad** [comment]
Module have been updated with a fix for this and updated to API version 1.6.11.
