### ISSUE TITLE
Autotask.ATWSSoapClient assembly not loaded

### ISSUE THREAD

**Issue by carterduplessis** [ecitsolutions/Autotask#121]
Thank you so much for the new release! The SOAP builds are a little beyond me so I really appreciate the work put in here.

When I upgraded to 2.0.2 and removed 2.0.1 I was faced with an error logging in. Upon using the Connect-ATWSWebAPI, it complained that in using the Connect-ATWSWebServices.ps1, the script references an assembly that is not loaded called Autotask.ATWSSoapClient. For some reason this went away after installing both 2.0.1 and 2.0.2.

![image](https://user-images.githubusercontent.com/91789171/218158406-1107a509-756f-4aae-8738-c824dc535e0f.png)

**Comment by RVL-Solutions** [comment]
Having the exact same issue since updating to version 2.0.2
Happening with both PS 5.1 and Pwsh 7

**Comment by klemmestad** [comment]
Sorry. The fix for assemblies on Powershell version 7.3.1+ creates this bug on earlier versions. I will fix this ASAP.

**Comment by klemmestad** [comment]
Version with fix on Powershell gallery already.

**Comment by TO360-isofer** [comment]
I'm having a similar error message now on version 2.01 and 2.0.3, haven't tried 2.0.2
```
Connect-AtwsWebAPI -Credential $Global:PSA.SecureCreds -ApiTrackingIdentifier $Global:PSA.ApiTrackingId -Ea Stop

New-Object : Cannot find an overload for "ATWSSoapClient" and the argument count: "2".
At C:\Program Files\WindowsPowerShell\Modules\Autotask\2.0.1\Private\Connect-AtwsWebServices.ps1:93 char:24
+ ... otService = New-Object Autotask.ATWSSoapClient  $anonymousBinding, $e ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
```
