### ISSUE TITLE
Unable to get udf filtering to work with Get-AtwsAccount

### ISSUE THREAD

**Issue by Shibby7986** [ecitsolutions/Autotask#51]
Hi, can anyone please let me know if this is an issue in my syntax or a bug?

I'm trying to get accounts that have a specified phone number within a user-defined field called 'SIPNumbers'
The field contains comma-separated phone numbers
i.e. 61859584521,61859426545,61858564586

I've tried the following...

using filter 
`Get-AtwsAccount -Filter {-udf 'SIPNumbers' -eq '61265666666'}`

it gives an error User Defined Field does not exist.

> Get-AtwsData : Invalid UDF field in query: sipnumbers' -eq '61265666666. User Defined Field does not exist.
> At line:848 char:15
> + ...   $Result = Get-AtwsData -Entity $EntityName -Filter $Filter -Connect ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData

It works if I use -UserDefinedField for a customer that only has one number but not with operators (i tried -Like)

Works: `Get-AtwsAccount -UserDefinedField @{name='SIPNumbers';value='61265666666'}`
Doesn't: `Get-AtwsAccount -UserDefinedField @{name='SIPNumbers';value='*61265666666*'} -Like UserDefinedField`

I get an error saying "UserDefinedField" does not belong to the set

> Get-AtwsAccount : Cannot validate argument on parameter 'Like'. The argument "UserDefinedField" does not belong to the set "Account
> Name,Address1,Address2,City,State,PostalCode,Country,Phone,AlternatePhone1,AlternatePhone2,Fax,WebAddress,AccountNumber,TaxID,Addit
> ionalAddressInformation,BillToAttention,BillToAddress1,BillToAddress2,BillToCity,BillToState,BillToZipCode,BillToAdditionalAddressI
> nformation" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
> At line:1 char:84
> + ... eld @{name='SIPNumbers';value='*61265666666*'} -Like UserDefinedField
> +                                                          ~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Get-AtwsAccount], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-AtwsAccount

**Comment by klemmestad** [comment]
Hi @Shibby7986, I’m sorry I am late to reply. Its been a crazy busy few weeks. At first glance this looks like two issues: a citation mark detection issue and missing functionality. I will look into both.

**Comment by klemmestad** [comment]
This should be solved now.
