### ISSUE TITLE
Update-ATWSFunctions typo

### ISSUE THREAD

**Issue by Superfluxus** [ecitsolutions/Autotask#55]
Pedantically small issue but the Update-ATWSFunctions cmdlet seems to have a typo on the word "Overwrite"

Output:

 Update-AtwsFunctions: About to create and oiverwrite Static functions for 77 entities. Do you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

**Comment by klemmestad** [comment]
Thank you for letting me know! It is nice to have something easy to fix for a change 😉

**Comment by Superfluxus** [comment]
My pleasure, thanks again for all your hard work on this invaluable tool :)

**Comment by klemmestad** [comment]
Fixed in the development branch
