### ISSUE TITLE
Searching by createdate

### ISSUE THREAD

**Issue by LedgerLand** [ecitsolutions/Autotask#57]
When searching for tickets created during the previous day using the following filter, I am getting results starting from 5am on the start date to 5am on the following day. I am not sure if this is an issue with the module or with Autotask itself. We are based in GMT and I have checked to ensure that Autotask is also set to GMT.

$Filter = "CreateDate -ge '08/10/2019 00:00:00' -and CreateDate -le '08/10/2019 23:59:59'"
$TicketList = Get-AtwsTicket -Filter $Filter

This returns

TicketNumber          CreateDate         
------------               ----------         
T2019XXXX.XXXX      08/10/2019 05:30:03
T2019XXXX.XXXX      08/10/2019 06:13:15
.....
.....
T2019XXXX.XXXX      09/10/2019 03:50:09
T2019XXXX.XXXX      09/10/2019 04:36:10

Is there somewhere in PowerShell that I should declare the Timezone as GMT so it's passed in the module?

Thanks in advance :-)

Rob

**Comment by Superfluxus** [comment]
Hi Rob,

$PSCulture will hold your timezone settings for Powershell

I've just tried to reproduce your bug using 'CreateDate -ge '21/10/2019 00:00:00' -and CreateDate -le '21/10/2019 **23:59:59' as the $FIlter variable, but it only picked up tickets raised on the 21st as expected.

It certainly does seem like a TimeZone issue if the results are out by 5 hours either side.

Lets get those checked:

**Autotask**

A -> Admin Menu ->Your Organziation -> Internal Locations.

Check these timezones against the resources that have made those 5am tickets, ensure that the TimeZone is set to GMT. They will correlate with 'Primary Internal Location' in the Resource page.

**PowerShell**

Check your Culture info with 'Get-Culture | Format-List -Property *' and check your timezone with Get-Timezone respectively.

I would suspect that your Powershell is configured fine, but your AutoTask resource (hopefully not the default internal location) is set to EST, as opposed to GMT.

Another way to check this would be to make a test ticket, or test ticket note, and then check the CreateDateTime property in Get-ATWSTicket or Get-ATWSTicketNote

I'll subscribe to this thread so I get notified of your reply, sorry for the radio silence!

Best,

Dan

**Comment by klemmestad** [comment]
The root cause of this problem is that the Autotask API _by design_ works in CEST _only_. It does not make any difference to the API which TimeZone you are using in the WebApp. When you make a query with a hardcoded -Filter I cannot (or at least haven't figured out how to) detect your dates as DateTime, so they get passed to the API as is. The API reads your DateTime as CEST and returns tickets based on that.

Any returned DateTime fields are converted to localtime by the module. That is why you get this behavior.

Workarounds:

1. Full control:
```powershell
# Format any date as sortable datetime format and include timezone info
# This will override the CEST default in the API
$Filter = "CreateDate -ge 2019-10-08T00:00:00+0 -and CreateDate -le 2019-10-08T23:59:59.0000+0"
$TicketList = Get-AtwsTicket -Filter $Filter
$TicketList | Select-Object TicketNumber, CreateDate 
```

2. The easiest:
```powershell
# If you pass a date, i.e. any datetime where $datetime -eq $datetime.date I expand it
# to a date filter
$TicketList = Get-AtwsTicket -CreateDate  (Get-Date).AddDays(-1).Date
$TicketList | Select-Object TicketNumber, CreateDate 
```

**Comment by LedgerLand** [comment]
Thanks for the replies!

I thought this may have been the case where AT was working on the basis of everything being CEST. Now I know, I can adjust the values being fed it accordingly.

Thanks again for the help :-)
