### ISSUE TITLE
Unable to set Issue/SubIssue when Subissue is on index 0

### ISSUE THREAD

**Issue by Napervillian** [ecitsolutions/Autotask#59]
Not sure how exactly to describe this challenge, but I am running this command:

`Get-ATWSTicket -TicketNumber $CurrentTicketNumber | Set-ATWSTicket -IssueType $IssueUpdateValue -subissueType $SubIssueUpdateValue`

This works for most cases, but for each Subissue picklist the first picklist value returns the following error. Any other picklist value is able to complete successfully. This is the error that is received:

Exception calling "update" with "1" argument(s): "There was an error generating the XML document."
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.2.17\Private\Set-AtwsData.ps1:76 char:7
+       $Result = $atws.update($WorkingSet)
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
 
Get-AtwsFieldInfo : Cannot bind argument to parameter 'Entity' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.2.17\Private\Set-AtwsData.ps1:132 char:49
+ ... tityInfo = Get-AtwsFieldInfo -Entity $Result.EntityResultType -Entity ...
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AtwsFieldInfo], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-AtwsFieldInfo

**Comment by Napervillian** [comment]
not sure if I am just referencing this incorrectly but I tried a few different ways and ended up with the same error every time.

**Comment by klemmestad** [comment]
Thank you for reporting this. I can reproduce it, it is definitely a bug. I haven't filtered out inactive picklist values. Trying to fix it now.

**Comment by klemmestad** [comment]
Fixed in current release (1.6.4.2)
