### ISSUE TITLE
Import-Module : Could not connect to Autotask WebAPI.

### ISSUE THREAD

**Issue by Largehawiian** [ecitsolutions/Autotask#60]
Autotask updated some things recently. Since then I've not been able to connect using the AT module. It's reporting incorrect credentials. I've verified my creds and API key. Using the same connection script block I always have. Any ideas ? 

_____________________________________________________________________________________________
Import-Module : Could not connect to Autotask WebAPI. Verify your credentials. If you are sure you have the rights - maybe you typed your password wrong?
At line:1 char:1
+ Import-Module Autotask -ArgumentList $Credential, $ApiKey -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Import-Module], ApplicationException
    + FullyQualifiedErrorId : Could not connect to Autotask WebAPI. Verify your credentials. If you are sure you have the rights - maybe you typed your password wrong?,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by Napervillian** [comment]
Have you tried running two separate commands and see which one sticks? try doing 

`import-module autotask`

And then afterwards

`connect-atwswebapi`

It should auto-prompt you for credentials and your API key.

**Comment by klemmestad** [comment]
This happens to me to from time to time, but it is usually related to the .NET webservice proxy that New-WebServiceProxy creates in .NET "outside" your powershell session. To successfully access the resources exported by the webservice proxy I have to use a consistent namespace. If the connection in this namespace fails somehow I am unable to make it work again without a reboot of the machine. The best option going forward is adding the option to choose your namespace yourself. this would also make it possible to connect to multiple autotask tenants simultanously, but it touches a lot of core functionality and will need extensive testing.

**Comment by klemmestad** [comment]
This problem should hopefully disappear completely from module version 1.6.5 wich is i beta3 now and quite stable. Just waiting for API version 1.6.5 to be released in my region.
