### ISSUE TITLE
Not all projects pulled with Get-AtwsProject

### ISSUE THREAD

**Issue by NickSalacious** [ecitsolutions/Autotask#62]
Using `get-atwsproject -all` I only receive 171 results. I know there are hundreds more. Even searching by ProjectNumber for an existing project number doesn't return a result. It seems limited or restricted some how.

**Comment by klemmestad** [comment]
I cannot reproduce this bug. Any chance this is a permission issue? Does your company use Lines of business, for instance? If your API user has all the same permissions as you web gui user the result should be the same. get-atwsproject -all should return all projects, regardless of active/inactive status.

**Comment by NickSalacious** [comment]
Thanks for checking. I haven't had the chance to investigate further but I will definitely check the permissions.
