### ISSUE TITLE
Data type convertion error on Get-AtwsTicketCost

### ISSUE THREAD

**Issue by gmandsberg** [ecitsolutions/Autotask#63]
Hi 

I'm seeing issues when using the "BillableToAccount" parameter on Get-TicketCost
"Billed" and "BillableTOAccount" is both boalean values and using "Billed" is working just fine, but when trying to filter on "BillableToAccount" I get a datatype conversion error - please see below. 

//gmandsberg

PS C:\Users\xxx-admin> $MyItems = Get-AtwsTicketCost -Name 'Mileage' -Billed $false -BillableToAccount $true
Get-AtwsData : Conversion failed when converting the varchar value 'true' to data type int.
At C:\Users\gma-admin\Documents\WindowsPowershell\Cache\808211\Dynamic\Get-AtwsTicketCost.ps1:499 char:17
+       $Result = Get-AtwsData -Entity $EntityName -Filter $Filter `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData
 

PS C:\Users\xxx-admin> $MyItems = Get-AtwsTicketCost -Name 'Mileage' -Billed $false -BillableToAccount 0
Get-AtwsData : Conversion failed when converting the varchar value 'false' to data type int.
At C:\Users\gma-admin\Documents\WindowsPowershell\Cache\808211\Dynamic\Get-AtwsTicketCost.ps1:499 char:17
+       $Result = Get-AtwsData -Entity $EntityName -Filter $Filter `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData

**Comment by klemmestad** [comment]
Definitely a bug. A fix is in the pipeline.
