### ISSUE TITLE
Importing Functions Hangs

### ISSUE THREAD

**Issue by AceOfNitwits** [ecitsolutions/Autotask#64]
Running Import-Module works sporadically. Often it hangs after the following is displayed:

> Creating and importing functions for all Autotask entities with picklists..
Entity 64/64 (100%), Importing WorkTypeModifier.

![image](https://user-images.githubusercontent.com/59476593/71725099-c2b8f380-2e00-11ea-9a3f-c716eb68503c.png)

**Comment by AceOfNitwits** [comment]
Should have mentioned, this occurs with version 1.6.2.17.

**Comment by klemmestad** [comment]
Updated version is out. please report if issue still persists.
