### ISSUE TITLE
Set-AtwsTicket - Failing and no XML

### ISSUE THREAD

**Issue by TimBrown-CCS** [ecitsolutions/Autotask#65]
`Set-AtwsTicket -ID $TicketID -Priority $ticket.priority -Status $ticket.status`
I have tried this on 2 different instances of Autotask. On one it works every time, on the other it throws errors.

`Exception calling "update" with "1" argument(s): "There was an error generating the XML document."
At C:\Modules\User\Autotask\Private\Set-AtwsData.ps1:76 char:7
+       $Result = $atws.update($WorkingSet)
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
 
Get-AtwsFieldInfo : Cannot bind argument to parameter 'Entity' because it is an empty string.
At C:\Modules\User\Autotask\Private\Set-AtwsData.ps1:132 char:49
+ ... tityInfo = Get-AtwsFieldInfo -Entity $Result.EntityResultType -Entity ...
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AtwsFieldInfo], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-AtwsFieldInfo`

Any ideas what is causing this?

**Comment by klemmestad** [comment]
This is possibly related to issue #59 which was fixed in todays new release. If possible, could you update your module and try again? In the previous version of the module I didn't know I needed to filter out inactive picklist options. This should be fixed. This is consistent with the module behaving differently with different tenants, as picklists are always dependent on tenant settings.

**Comment by klemmestad** [comment]
I haven't heard anything so I am going to assume the issue is fixed.

**Comment by TimBrown-CCS** [comment]
Sorry, hadn't had a chance to test it yet. I will assume it's fine as your explanation makes sense. :)

**Comment by klemmestad** [comment]
Don't hesitate to re-open if the issue persist 😉
