### ISSUE TITLE
Still getting 'updating disk cache' on every module import

### ISSUE THREAD

**Issue by ArtisanByteCrafter** [ecitsolutions/Autotask#66]
Hi,

I noticed that issue #33 addressed an issue where the disk cache was fully updated on every module import. Unfortunately I seem to still be having this problem, and as a result, each import is about 60 seconds. This naturally makes testing and automation take quite long.

I'm using version 1.6.2.17

If there's anything i can do to help, please let me know. Thanks!

**Comment by JanDurryCyberdyne** [comment]
I am experiencing the same issue. Plus the import fails on remote, as the confirmation message is prompted on execution.

Any ideas?

**Comment by jameseleach** [comment]
I too am experiencing this.

I've removed the module, deleted the cache and reinstalled the module, to no effect.   I've tried installing the module both with elevated privileges and without (-Scope CurrentUser).

**Comment by ArtisanByteCrafter** [comment]
In testing, I had some luck reverting back to version `1.6.2.4`. If i import this version once to build a cache, then import it again, it seems to honor the cache in the future.

I get a similar error to @jameseleach from 1.6.2.17 here:

```
DEBUG: Autotask.psm1: Personal disk cache: Found 0 script files in
C:\Users\username\Documents\WindowsPowershell\Cache\301126\Dynamic
Select-String : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\username\Documents\WindowsPowerShell\Modules\Autotask\1.6.2.17\Autotask.psm1:176 char:74
+ ... Select-String -Pattern $VersionString -Path $DynamicFunction.FullName
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Select-String], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SelectStrin     gCommand

DEBUG: Autotask.psm1: Personal disk cache: Wrong number of script files or scripts are not the right version in         C:\Users\username\Documents\WindowsPowershell\Cache\301126\Dynamic, refreshing all entities.
Remove-Item : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\username\Documents\WindowsPowerShell\Modules\Autotask\1.6.2.17\Autotask.psm1:181 char:43
+ ...           $Null = Remove-Item -Path $DynamicFunction.fullname -Force  ...
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RemoveItemC     ommand
```

**Comment by klemmestad** [comment]
Hi guys,
I've been very quiet the last few months, nothing wrong, just an insane amount of work in my primary job functions. The good news is that I have an updated code tree with fixes for this and other issues, and it is FINALLY! passing my new pester tests. Which means that it should hopefully not re-open old bugs, but it may still open new ones...
Also, there are still open issues I haven't written pester tests for yet, so I do not know if I will solve all issues (probably not), but I do know I have a fix for this specific issue.

**Comment by JanDurryCyberdyne** [comment]
My workaround at the moment is using version `1.6.2.1` and specify the
`$global:ConfirmPreference = "None"`. Does that work for someone else too?

**Comment by klemmestad** [comment]
Module 1.6.4.2 should fix this issue. On PowershellGallery now.
