### ISSUE TITLE
Problems with long phone numbers and tax id's

### ISSUE THREAD

**Issue by tmidthjell** [ecitsolutions/Autotask#68]
I've encountered multiple problems with large/long phone numbers and Tax ID's. The problem is with ConvertFrom-XML. I've been able to fix the problem by increasing it to Int64

Line 95 in convertfrom-xml
Not working: [Int]$Integer = $Element.$PropertyName
Working: [Int64]$Integer = $Element.$PropertyName

You can replicate the error by using a tax id higher than the maximum int and running the function: Get-AtwsInvoiceInfo against the company with the high tax id or phone number.

**Comment by klemmestad** [comment]
Hi,
This has been fixed in the latest version (v 1.6.4.2), released end of January. If you update your module you should get the fix (and a bunch of other bugfixes).
