### ISSUE TITLE
experiencing problems utilizing the commandlets

### ISSUE THREAD

**Issue by aciesler** [ecitsolutions/Autotask#69]
When I authenticate using Connect-AutotaskWebAPI -Credential $ATPCredObject -ApiTrackingIdentifier $ATPSAAPIID I get the following response. I am unable to use any powershell commands. Please help me understand what I am doing incorrectly.

Exception calling "Create" with "1" argument(s): "At line:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing closing ')' in expression.
At line:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Parameter declarations are a comma-separated list of variable names with optional initializer expressions.
At line:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing ')' in function parameter list.
At line:11 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition."
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.4.2\Private\Import-AtwsCmdLet.ps1:103 char:21
+                     . ([ScriptBlock]::Create($function.Value))
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
 
Exception calling "Create" with "1" argument(s): "At line:90 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing closing ')' in expression.
At line:90 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Parameter declarations are a comma-separated list of variable names with optional initializer expressions.
At line:90 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing ')' in function parameter list.
At line:11 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition."
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.4.2\Private\Import-AtwsCmdLet.ps1:103 char:21
+                     . ([ScriptBlock]::Create($function.Value))
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
 
Exception calling "Create" with "1" argument(s): "At line:121 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing closing ')' in expression.
At line:121 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Parameter declarations are a comma-separated list of variable names with optional initializer expressions.
At line:194 char:65
+ ... g {1} {2}(s)' -F $MyInvocation.MyCommand.Name, $ModifiedObjects.count ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The string is missing the terminator: '.
At line:121 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing ')' in function parameter list.
At line:11 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition."
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.4.2\Private\Import-AtwsCmdLet.ps1:103 char:21
+                     . ([ScriptBlock]::Create($function.Value))
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
 
Exception calling "Create" with "1" argument(s): "At line:359 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing closing ')' in expression.
At line:359 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Parameter declarations are a comma-separated list of variable names with optional initializer expressions.
At line:359 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing ')' in function parameter list.
At line:11 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition."
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.4.2\Private\Import-AtwsCmdLet.ps1:103 char:21
+                     . ([ScriptBlock]::Create($function.Value))
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
 
Exception calling "Create" with "1" argument(s): "At line:134 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing closing ')' in expression.
At line:134 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Parameter declarations are a comma-separated list of variable names with optional initializer expressions.
At line:207 char:65
+ ... g {1} {2}(s)' -F $MyInvocation.MyCommand.Name, $ModifiedObjects.count ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The string is missing the terminator: '.
At line:134 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing ')' in function parameter list.
At line:11 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition."
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.4.2\Private\Import-AtwsCmdLet.ps1:103 char:21
+                     . ([ScriptBlock]::Create($function.Value))
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
 
Exception calling "Create" with "1" argument(s): "At line:111 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing closing ')' in expression.
At line:111 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Parameter declarations are a comma-separated list of variable names with optional initializer expressions.
At line:111 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing ')' in function parameter list.
At line:11 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition."
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.4.2\Private\Import-AtwsCmdLet.ps1:103 char:21
+                     . ([ScriptBlock]::Create($function.Value))
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParseException
 
Import-Module : Could not import function C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1: At 
C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing closing ')' in expression.
At C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Parameter declarations are a comma-separated list of variable names with optional initializer expressions.
At C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing ')' in function parameter list.
At C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1:11 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition.
At C:\Program Files\WindowsPowerShell\Modules\autotask\1.6.4.2\Public\Connect-AtwsWebAPI.ps1:167 char:13
+             Import-Module -Name $moduleName @importParams
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not impor...ype definition.:String) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : Could not import function C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1: At C:\Users\andy\Documents\ 
   WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing closing ')' in expression.
At C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Parameter declarations are a comma-separated list of variable names with optional initializer expressions.
At C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1:338 char:3715
+ ... : Setup', 'Printer: WMIC commands', "Quickbooks and Outlook "You don' ...
+                                                                  ~
Missing ')' in function parameter list.
At C:\Users\andy\Documents\WindowsPowershell\Cache\301045\Dynamic\Get-AtwsChecklistLibraryChecklistItem.ps1:11 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition.,Microsoft.PowerShell.Commands.ImportModuleCommand
 
PS C:\WINDOWS\system32> get-atwsaccount
get-atwsaccount : The term 'get-atwsaccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ get-atwsaccount
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-atwsaccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Edited: Cut away what looked like an unintended posting of a password.

**Comment by klemmestad** [comment]
It looks like you have items in your checklist library that use both single and double quotes. I have not been advanced enough in my embedding of strings to be compatible with that. That is why the module import fails completely. You can still use the module, but you will miss the intellisens support. You can load it with `Connect-AtwsWebAPI <other required parameters> -NoDiskCache`. That will skip the creation of tenant specific functions with intellisense support.

I will have to figure out a safe and reversible encoding of special characters in strings to support this. It will need to be readable and predictable, too, but is should be doable.

**Comment by klemmestad** [comment]
This should be fixed in the current module version.
