### ISSUE TITLE
seeing services tied to a contract

### ISSUE THREAD

**Issue by aciesler** [ecitsolutions/Autotask#70]
Hello again. Using the get-atwscontract cmdlet I can see the contracts for an account but am I able to see into the services tied to the contract on a monthly basis?

**Comment by klemmestad** [comment]
This one is a bit difficult. To get any service connected with a contract you can do `Get-AtwsContractService -ContractId <id>`. But then you would only get Services. If you want bundles, too, you will have to do a second query `Get-AtwsContractServiceBundle -ContractId <id>`. But from there you will have to take into account period types, any adjustments made in a period, etc. So if what you want is a quick report on services, units, price and cost for a given month for any contract it is surprisingly difficult to figure out. I will hopefully get around to either do a write-up of how to do it or make a meta-function that does all the work. But I am afraid that is still months away.

**Comment by aciesler** [comment]
Hi there! We've got a monthly routine that I wanted to automate for a customer. In the contract beginning at each month, there are services that have a quantity change each month. I know what the servies are though. I was hoping to fully automate the monthly routine and be able to touch the service quantities on the contract. Based on that information, do you think the module supports it?

Andy Ciesler
Co-Director of Technology
& senior systems engineer
ofc: 419.740.7150
hd: 419.842.8410
