### ISSUE TITLE
Unable to connect to secondary/sandbox database

### ISSUE THREAD

**Issue by Superfluxus** [ecitsolutions/Autotask#71]
Hi,

We have two databases with Autotask, one for Production and another for our Sandbox. I am able to connect to our production DB absolutely fine with the Powershell module. However, when I use my Sandbox credentials for my API user, I get this error:

```
Import-Module : The specified module 'C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17' with version '1.6.2.17' was not loaded because no
valid module file was found in any module directory.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Connect-AtwsWebAPI.ps1:179 char:9
+         Import-Module -Name $ModulePath @ImportParams
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...totask\1.6.2.17:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

```

The filepath is absolutely fine, and works with my production credentials. For what it's worth, the module fails out immeditaely as it gets past 'Authenticating to Web Service' and just as it starts 'Testing connection'.

I have made two brand new API users on our sandbox DB, and they get locked out as resources after the attempts fail, but the authentication just won't get through. 

Any ideas?

**Comment by klemmestad** [comment]
I have had similar errors reported from others using module version 1.6.2.17. The latest release is version 1.6.4.2. Could you try that version and see if it makes any difference? I also have a beta version (`Install-Module Autotask -AllowPreRelease`) that is compatible with PowerShell versions 6 and 7 while still working with PowerShell 4 and up. It _should_ be more compatible with dual database scenarios, but it hasn't been tested enough to be released yet. It performs very well in our testing so far, though.

**Comment by Superfluxus** [comment]
I have updated the module to 1.6.4.2 and it works flawlessly, this seems to have solved our issue. Thankyou very much!
