### ISSUE TITLE
Is there a way to skip personal cache on module import?

### ISSUE THREAD

**Issue by ArtisanByteCrafter** [ecitsolutions/Autotask#77]
I see references to -NoDiskCache, and a `$centralCache` variable that points to the file 'AutotaskFieldInfoCache.xml` in the /private folder, but I can't seem to find where this parameter is specified.

I'm running into issues trying to import this module under the NT\System context, which is the context I need to run as. The personal cache seems to try to store itself under MyDocuments, which of course NT\System does not have.

Any advice on how to be able to import the module (along with all exported functions) without using a PersonalDiskCache?

Here is the issue I get when trying to import module 1.6.5 under NT\System

```
VERBOSE: Get-AtwsData: Passing QueryXML to Autotask API
VERBOSE: Import-AtwsDiskCache: trying to determine correct location for dynamic
 module cache.
VERBOSE: Import-AtwsDiskCache: Module cache location is C:\Program 
Files\WindowsPowerShell\Modules\Autotask\1.6.5\Private\AutotaskFieldInfoCache.x
ml
Import-Module : Cannot bind argument to parameter 'Path' because it is an 
empty string.
Stacktrace:
at Import-AtwsDiskCache<Begin>, C:\Program Files\WindowsPowerShell\Modules\Auto
task\1.6.5\Private\Import-AtwsDiskCache.ps1: line 48
at Get-AtwsFieldInfo<Begin>, C:\Program 
Files\WindowsPowerShell\Modules\Autotask\1.6.5\Public\Get-AtwsFieldInfo.ps1: 
line 111
at ConvertTo-LocalObject<Process>, C:\Program Files\WindowsPowerShell\Modules\A
utotask\1.6.5\Private\ConvertTo-LocalObject.ps1: line 60
at Get-AtwsData<Process>, C:\Program 
Files\WindowsPowerShell\Modules\Autotask\1.6.5\Private\Get-AtwsData.ps1: line 
124
at Connect-AtwsWebServices<Process>, C:\Program Files\WindowsPowerShell\Modules
\Autotask\1.6.5\Private\Connect-AtwsWebServices.ps1: line 215
at <ScriptBlock>, C:\Program 
Files\WindowsPowerShell\Modules\Autotask\1.6.5\Autotask.psm1: line 134
at <ScriptBlock>, <No file>: line 1
At line:1 char:1
+ Import-Module Autotask -ArgumentList $Credential, $ApiKey -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Import-Module], ProviderE 
   xception
    + FullyQualifiedErrorId : Cannot bind argument to parameter 'Path' because 
    it is an empty string.
Stacktrace:
    at Import-AtwsDiskCache<Begin>, C:\Program Files\WindowsPowerShell\Modules 
   \Autotask\1.6.5\Private\Import-AtwsDiskCache.ps1: line 48
    at Get-AtwsFieldInfo<Begin>, C:\Program Files\WindowsPowerShell\Modules\Au 
   totask\1.6.5\Public\Get-AtwsFieldInfo.ps1: line 111
    at ConvertTo-LocalObject<Process>, C:\Program Files\WindowsPowerShell\Modu 
   les\Autotask\1.6.5\Private\ConvertTo-LocalObject.ps1: line 60
    at Get-AtwsData<Process>, C:\Program Files\WindowsPowerShell\Modules\Autot 
   ask\1.6.5\Private\Get-AtwsData.ps1: line 124
    at Connect-AtwsWebServices<Process>, C:\Program Files\WindowsPowerShell\Mo 
   dules\Autotask\1.6.5\Private\Connect-AtwsWebServices.ps1: line 215
    at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6. 
   5\Autotask.psm1: line 134
    at <ScriptBlock>, <No file>: line 1,Microsoft.PowerShell.Commands.ImportMo 
   duleCommand
```

**Comment by ArtisanByteCrafter** [comment]
another option might be to add a Parameter that allows the Cache location to be defined at module import.

```powershell
$Credential = (Get-Credential)
$ApiKey = '12345'
$CacheFolder = "$env:systemdrive\AtwsCacheFolder"
Import-Module Autotask -ArgumentList $Credential,$ApiKey,$CacheFolder
```

or similar

**Comment by klemmestad** [comment]
Good idea, @ArtisanByteCrafter! 

However, adding more parameters to -Argumentlist is a pain because you only get positional information. It is much easier (and more reliable) to add such a feature to the Connect-AtwsWebAPI. Which already supports `-NoDiskCache`, btw. 

To load the module without disk cache (which you do not need for batch jobs, only for coding) load the module and connect in two steps:
```powershell
Import-Module Autotask
Connect-AtwsWebAPI -NoDiskCache -Credential $Credential -ApiTrackingIdentifier $ApiKey 
```

**Comment by ArtisanByteCrafter** [comment]
Hi Hugo, thanks for the update, that's great information. At first glance, importing the module first, then connecting separately seems to have resolved my issue running under NT\System.

Just to clarify, when you specify `-NoDiskCache` am I correct that it uses the file `\Private\AutotaskFieldInfoCache.xml` as the source for creating and importing the dynamic functions? And when you release new versions of the module that are based on new versions of the API, you update this file with the new cmdlets?

I just want to better understand how the module works, as I'm relatively new to using it.

Thanks!

**Comment by klemmestad** [comment]
Yes, you are partly correct. With `-NoDiskCache` you import the `\Private\AutotaskFieldInfoCache.xml` at module load to initialize the entity information cache, but the in-memory cache will still be updated from the API at run time.

**Comment by ArtisanByteCrafter** [comment]
Thanks for the info! I'm going to consider this resolved.
