### ISSUE TITLE
Contact UDF's Missing

### ISSUE THREAD

**Issue by MadRainbow** [ecitsolutions/Autotask#79]
Have managed to have my powershell script working for about a week now, to update CONTACT UDF's.

Yesterday, I started to get errors 

`Set-AtwsContact : A parameter cannot be found that matches parameter name 'UserDefinedFields'.`

When running `get-atwscontact -id $ContactID | Set-AtwsContact -UserDefinedFields @{name=$Ref2; value=$Value}`

I've removed the module, reinstalled, refreshed the cache a hundred times, but it seems to have gone screwey

When I run `Get-AtwsFieldInfo -Entity Contact -EntityInfo`, AT returns

> Name                    : Contact
> CanUpdate               : True
> CanDelete               : True
> CanCreate               : True
> CanQuery                : True
> HasUserDefinedFields    : False
> SupportsWebhookCallouts : False

The part that concerns me is "HasUserDefinedFields: False".

Any thoughts on how to fix this?

Thanks

David

**Comment by klemmestad** [comment]
That is definitely an issue and may require a module update to fix. I have seen this in testing before the recent API upgrade, but the problem disappeared completely after that. I will need at least a day to test and verify, will let you know what I find.

**Comment by MadRainbow** [comment]
Thanks for the update, and hope you are keeping yourself safe

I am slightly relieved that it wasn't my dodgy coding!

Thanks ever so much for your help.

Kind regards

David

**Comment by klemmestad** [comment]
I definitely had the issue now, too. I have made a fix and published an updated module. Not much other improvements, but anyone who wants to access Userdefined Fields will have to upgrade.

Thank you for reporting this!

**Comment by MadRainbow** [comment]
Works like a dream!  Thank you!

D
