### ISSUE TITLE
problems adding a new quote

### ISSUE THREAD

**Issue by aciesler** [ecitsolutions/Autotask#80]
I'm using the new-atwsquote command on version 1.6.6 and it won't let me complete the quote without a -billtolocationid, -shiptolocationid and -soldtolocationid. I have contracts where this is blank but I feel like I've been through all of the account related commandlets and can't find this information anywhere. Is it a glitch? Walking through the UI I'm not prompted for information regarding locations.

**Comment by klemmestad** [comment]
Unfortunately those fields are marked Required by the API. All three seems to reference the same entity, QuoteLocation. There are commandlets for quotelocation, so you should be able to find and even create them through those.

**Comment by aciesler** [comment]
Is there a better way to ask questions like this where it may seem more like support than a technical issue with the module?

Andy Ciesler
Co-Director of Technology
& senior systems engineer
ofc: 419.740.7150
hd: 419.842.8410

**Comment by JsonWud** [comment]
Hi Andy,

Having the API documentation handy and using the Get-AtwsFieldInfo command can be helpful to learn which parameters are required and other useful information such as data types and maximum character length on string properties. I use it quite often while I'm developing, like so:

Get-AtwsFieldInfo -Entity Quote | Out-GridView

Also, here's a link to the API doc which will also include required data and string limitations:

https://ww4.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_6.pdf

Best,
Jason
