### ISSUE TITLE
Not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ankbomb** [ecitsolutions/Autotask#81]
In Azure Automation, using 1.6.6 

I can import-module
import-module Autotask
Connect-AtwsWebAPI -Credential $cred -ApiTrackingIdentifier $ApiAutotaskKey

Get-AtwsAccount -CreateDate 3/1/2020 -GreaterThan CreateDate

....

System.Management.Automation.CommandNotFoundException: The term 'New-AtwsAccount' is not recognized as the name of a cmdlet

seems similar to this from @kai-osthoff:

It seems working now, but ...
System.Management.Automation.CommandNotFoundException: The term 'New-AtwsTicket' is not recognized as the name of a cmdlet, 

... the "New-AtwsTicket"-CMDlet is missing!

Kai

_Originally posted by @kai-osthoff in https://github.com/ecitsolutions/Autotask/issues/17#issuecomment-492997359_

**Comment by klemmestad** [comment]
Hi @ankbomb,
In Azure Automation you'll want to load the module using the `-NoDiskCache` option like this:
```powershell
import-module Autotask
Connect-AtwsWebAPI -Credential $cred -ApiTrackingIdentifier $ApiAutotaskKey -NoDiskCache
```
A runbook or a batch job does not need customized functions for your tenant, they will function just fine with the pre-built functions supplied with the module.

**Comment by ankbomb** [comment]
Same error when I add the `-NoDiskCache`

**Comment by ankbomb** [comment]
Also, confirming that the APIKey is working and connecting outside of Azure Automation

**Comment by klemmestad** [comment]
Weird! It works just fine in our Automation accounts. I will look into it.

**Comment by ankbomb** [comment]
Looks like I had to use the 26 character key.
