### ISSUE TITLE
-NoDiskCache regression in 1.6.6 in Azure Automation?

### ISSUE THREAD

**Issue by joncz** [ecitsolutions/Autotask#83]
I've read through the issues list and found -NoDiskCache and it seems the connection is ignoring the switch:

`
Stacktrace:

at Import-AtwsDiskCache<Begin>, D:\home\data\ManagedDependencies\200610155955768.r\Autotask\1.6.6\Private\Import-AtwsDiskCache.ps1: line 48
at Get-AtwsFieldInfo<Begin>, D:\home\data\ManagedDependencies\200610155955768.r\Autotask\1.6.6\Public\Get-AtwsFieldInfo.ps1: line 111
at ConvertTo-LocalObject<Process>, D:\home\data\ManagedDependencies\200610155955768.r\Autotask\1.6.6\Private\ConvertTo-LocalObject.ps1: line 60
at Get-AtwsData<Process>, D:\home\data\ManagedDependencies\200610155955768.r\Autotask\1.6.6\Private\Get-AtwsData.ps1: line 124
at Connect-AtwsWebServices<Process>, D:\home\data\ManagedDependencies\200610155955768.r\Autotask\1.6.6\Private\Connect-AtwsWebServices.ps1: line 215
at <ScriptBlock>, D:\home\data\ManagedDependencies\200610155955768.r\Autotask\1.6.6\Autotask.psm1: line 134
at Connect-AtwsWebAPI<Process>, D:\home\data\ManagedDependencies\200610155955768.r\Autotask\1.6.6\Public\Connect-AtwsWebAPI.ps1: line 187
at Get-WarrantyAutotask, D:\home\site\wwwroot\Get-ATWarranty\run.ps1: line 308
`

`
307    #Import-Module Autotask -ArgumentList $Credential, $APIKey
308    Connect-AtwsWebApi -NoDiskCache -Credential $Credential -ApiTrackingIdentifier $APIKey

`

**Comment by klemmestad** [comment]
Thank you, @joncz!
I will move that check into the UseDiskCache section. I erroneously assumed Known Folders would always be present on Windows. Not so. We use the module in Azure Automation ourselves, but only on remote workers (an ERP dependency in our case), so I didn't catch it.

I will release an update shortly, fixing this and a part of issue #61.

**Comment by klemmestad** [comment]
Module version 1.6.7 is out with a fix for this. Hope it works for you!
