### ISSUE TITLE
ConvertFrom-XML - Slow (Get-AtwsInvoiceInfo)

### ISSUE THREAD

**Issue by tmidthjell** [ecitsolutions/Autotask#84]
Hi, when running Get-AtwsInvoiceInfo the ConvertFrom-XML seems to be the bottleneck. I've been digging into the function, and I think it might actually be the XML format itself that is the bottleneck, but if you or any others have any ideas in how to improve performance in this function that would be great

**Comment by klemmestad** [comment]
Hi, you are probably spot on. The .GetInvoiceMarkup() API call only supports 2 formats, html and xml. It is easier to code using xml, but the resulting code is slow. Additionally the API call only supports a single invoiceid pr call. That makes things even slower when you are working with an entire invoice batch, for instance.

We could rewrite the Get Invoice part to use other entities, but there are quite a few entities involved; invoice, account, contract, resource, billingitem, allocationcode, timeentry and more. Getting all invoiceinfo that way would probably be faster for large invoice batches, but it is a lot of work for a problem that has a working, albeit a slow solution.

My plan is to revisit the challenge when the REST version of the API is released this month. So far I know next to nothing about it, but I do hope speed will be one of the things it improves 😊

**Comment by tmidthjell** [comment]
Awesome. I'm really looking forward to the release of REST :)
