### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by dahifi** [ecitsolutions/Autotask#85]
FInally! Good bye SOAP! 

https://www.reddit.com/r/msp/comments/h7ipu2/automating_with_powershell_autotask_psa_rest_api/

**Comment by KelvinTegelaar** [comment]
@klemmestad I am able to grant sandbox access, if you'd like. The date for london has been moved to 17th of july. I'm there too.

**Comment by bjowol** [comment]
TYI: REST support for the module, or rather converting the whole module too rest is currently a low priority task, but we will get there. The speed difference from rest and soap is not much, in some cases the SOAP API is actually faster, and vise versa.
