### ISSUE TITLE
Is the SOAP API Dead?

### ISSUE THREAD

**Issue by AceOfNitwits** [ecitsolutions/Autotask#86]
Since the last week, I have been unable to use either the beta or the current release. When connecting, I get 
[##############################] 100 % - Done
but it never progresses from there.
This occurs with PS 5.1 and 7.0.

**Comment by klemmestad** [comment]
I have no such issues at my end. Any -Verbose output that may help?

**Comment by bjowol** [comment]
@AceOfNitwits you figure it out?

**Comment by bjowol** [comment]
> @AceOfNitwits you figure it out?
