### ISSUE TITLE
Query on Ticket Status shows strange result

### ISSUE THREAD

**Issue by HarryPieterse** [ecitsolutions/Autotask#90]
When checking the status of a ticket I get a status value of 5.
When then checking the thicket based on that value I get an error:
![afbeelding](https://user-images.githubusercontent.com/8652176/95825995-f7fc5580-0d31-11eb-8fd0-4408653d324f.png)

TYhis list contains statussen that are not (all) configured in our system.
Even, when checking the datawarehousedata on the status id I get back, is is not the id of the status that the ticket is set to.

Am I doing something wrong or misunderstanding the use of the query?

Please advise

**Comment by bjowol** [comment]
@HarryPieterse  The string value of the Status property should have a Label suffix added to the returned object (StatusLabel). You cannot search for the int id value anymore. Changes some time back, dont know any details. You have to write the string value as the module converts it yo your tenant unique string value. Use intellisense to display your options.
![image](https://user-images.githubusercontent.com/14833255/96453722-2c34b200-121b-11eb-9d5c-37439ee3fe9d.png)

You can write your own -Filter clause though.
`Get-AtwsTicket -Filter "id -eq 45684 -and Status -eq 5"`

**Comment by bjowol** [comment]
@HarryPieterse Dis my last response help you at all? did you figure it out?

**Comment by HarryPieterse** [comment]
Hi Björn,

Just found back your mail, I must have overloper.
Yes this helps me a lot. Thanks for your help and the provision os zich a great module!!


Great job in that.
Have a nice weekend ahead

Kind regards

Harry Pieterse



________________________________
