### ISSUE TITLE
The HTTP request is unauthorized with client authentication scheme 'Basic'

### ISSUE THREAD

**Issue by SBartley08** [ecitsolutions/Autotask#92]
I receive the below error when trying to connect to Autotask with the latest version of the module ERROR: Exception calling "query" with "2" argument(s): "The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic Realm="webservices4.autotask.net"'."

I was using 0.2.2.1 previously and that connected fine.

**Comment by bjowol** [comment]
@SBartley08 are you connecting with a API Tracking Identifer? 
either way, can you post the code you are using to connect?

**Comment by SBartley08** [comment]
This is how im trying to connect (credentials are my Autotask username and password), I have also changed the path to XXXX to hide some infomation.

Connect-AutotaskWebAPI

cmdlet Connect-AtwsWebAPI at command pipeline position 1
Supply values for the following parameters:
Credential
ApiTrackingIdentifier: powershell
ERROR: Exception calling "query" with "2" argument(s): "The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic Realm="webservices4.autotask.net"'."

Stacktrace:
at Get-AtwsData<Process>, C:\Users\XXXXX\Documents\WindowsPowerShell\Modules\Autotask\1.6.10\Private\Get-AtwsData.ps1: line 112
at Connect-AtwsWebServices<Process>, C:\Users\XXXX\Documents\WindowsPowerShell\Modules\Autotask\1.6.10\Private\Connect-AtwsWebServices.ps1: line 215
at <ScriptBlock>, C:\Users\XXXX\Documents\WindowsPowerShell\Modules\Autotask\1.6.10\Autotask.psm1: line 134
at Connect-AtwsWebAPI<Process>, C:\Users\XXXX\Documents\WindowsPowerShell\Modules\Autotask\1.6.10\Public\Connect-AtwsWebAPI.ps1: line 187
at <ScriptBlock>, <No file>: line 1

**Comment by SBartley08** [comment]
Looking at it again I think I see what the issue is, I want to connect to the V1.5 of the API (without the api key) is there a way to do this with the latest module or do I need to use a old version ?

**Comment by bjowol** [comment]
@SBartley08 interesting. did not eaven know the 1.5 version still worked. The 1.6V requires an API tracking identifier, and cannot be empty. I dont know of any reason why anyone would stay behind on the 1.5v? why are you not using the 1.6v?

However, the module probably lost support for v1.5 at some point after 0.2.2.1, i dont know any details unfortunately. 
@klemmestad , you have anything to add to this?
@SBartley08 , mr. Klemmestad may not answer in a while, but worth a shot.

Im currently using the 2.0.0beta2 module myself, along with the API 1.6v. This module is a lot faster, and ps core enabled.

**Comment by SjoerdSlabbers** [comment]
I've tried various versions, including the beta. but when I try to connect I get the message: ERROR: Exception calling "query" with "2" argument(s): "The HTTP request is unauthorized with client authentication scheme 'Basic'. The authentication header received from the server was 'Basic Realm="webservices4.autotask.net"'."

I use the script below, but can't find the issue.

# Password setup
$ATpassword = ConvertTo-SecureString -String $ATapiUserPassword -AsPlainText -Force
$ATCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ATapiUserName, $ATpassword

# Import Module Refresh
Import-Module AutoTask -Argumentlist $ATCredential, $ATapiKey

# Connect
Connect-autotaskWebAPI -Credential $ATCredential -ApiTrackingIdentifier $ATapiKey

**Comment by klemmestad** [comment]
The message claims rather bluntly that either your username or password is wrong. Random guess: I have noticed that Autotask retains only the 15 first characters of any password. If you have used a longer one you may have to truncate it at 15 characters. Could this be your problem?

**Comment by SjoerdSlabbers** [comment]
ok, I changed the length to 14 characters. Still it didn't work. so I removed all ofther characters than letters and numbers, and the password works. If I use a password longer than 15, it always works when using interactive logon (get-credential).

**Comment by klemmestad** [comment]
So we may have a character encoding issue? I do not force any specific encoding in the SOAP client. I was kind of hoping that defaults would suffice...

**Comment by klemmestad** [comment]
@SjoerdSlabbers; if you do
`$binding = New-Object ServiceModel.BasicHttpsBinding`
`$binding.TextEncoding.EncodingName`
Do you get "Unicode (UTF-8)"? Is it the same as `$OutputEncoding.EncodingName`?

**Comment by SjoerdSlabbers** [comment]
```
$binding = New-Object ServiceModel.BasicHttpsBinding
$binding.TextEncoding.EncodingName
```
Gives; Unicode (UTF-8)

$OutputEncoding.EncodingName gives: Western European (Windows)

**Comment by klemmestad** [comment]
Thats is probably the default for PowerShell 5.1 on Windows. PowerShell Core has Unicode (UTF-8) as default on both. You had special characters in you password when it failed? If so, could you share the characters with me? So I could test if the different output encoding is the problem.

**Comment by SjoerdSlabbers** [comment]
the charcters were: !#@$

**Comment by klemmestad** [comment]
That is not characters that would be affected by encoding. Any chance you may have had a quoting mishap? Did the password variable have the correct length?

**Comment by SjoerdSlabbers** [comment]
I removed the characters and shortened the password both in one step. Might be that the password length was the issue

**Comment by bjowol** [comment]
>Might be that the password length was the issue
