### ISSUE TITLE
Charge Defaults

### ISSUE THREAD

**Issue by tmidthjell** [ecitsolutions/Autotask#95]
Hi
I'm trying to get all list of my Contract Charge Defaults through the API, but I cannot find an endpoint for it. I know it's not directly an issue with this module, but I'm posting this question anyway in the hopes of you might know the answer.

**Comment by HarryPieterse** [comment]
Hi All,

I’ve been looking fort hat some time ago but the contrcat charge defaults are not exposed in either the API nor the DataWareHouse daatabaes.

**Comment by tmidthjell** [comment]
Thanks for your reply @HarryPieterse. Right before your reply I requested access to the DataWareHouse, but then thats probably pointless :(

**Comment by msoukhomlinov** [comment]
@tmidthjell  and @HarryPieterse , here is confirmation: https://community.kaseya.com/PSA_service_desk/discussion/66841/autotask-rest-api-contract-charges-default

Here is the Feature Request: https://psa.ideas.datto.com/ideas/PSA-I-11125, seems like they shipped DW but not API portion. :( 

Please vote on this new feature request.
