### ISSUE TITLE
New-AtwsTicket  -Tags Parameter

### ISSUE THREAD

**Issue by AceOfNitwits** [ecitsolutions/Autotask#96]
Need to add a parameter to New-AtwsTicket to allow addition of ticket tags.

**Comment by klemmestad** [comment]
I have rebuilt the production module with support for the new API version. There are still no tag parameters for the new-atwsticket function. They have elected to support tags through a separate entity `TicketTagAssociation`. The command you are looking for is `New-AtwsTicketTagAssociation`. Available from module version 1.6.13 (published today).

**Comment by AceOfNitwits** [comment]
This is awesome. Thank you!
